# Generated by Django 4.1.4 on 2022-12-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppName', models.CharField(max_length=100)),
                ('AppLink', models.CharField(max_length=100)),
                ('AppCategory', models.CharField(choices=[('socialmedia', 'socialmedia'), ('office-meetings', 'office-meetings'), ('Important', 'Important')], default='Entertainment', max_length=100)),
                ('subcategory', models.CharField(choices=[('Entertainment', 'Entertainment'), ('videostreaming', 'videostreaming'), ('Community', 'Community'), ('fitness', 'fitness'), ('documents', 'documents')], default='SocialMedia', max_length=100)),
                ('AppImage', models.ImageField(blank=True, upload_to='')),
                ('Points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Apps', models.ManyToManyField(to='baseapp.apps')),
            ],
        ),
    ]
