# Generated by Django 4.1.4 on 2022-12-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Apps',
            new_name='InstalledApps',
        ),
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('owner', 'owner'), ('user', 'user')], default='user', max_length=12),
        ),
    ]
