# Generated by Django 4.1.4 on 2022-12-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_rename_apps_users_installedapps_users_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserPoints',
            field=models.IntegerField(default=0),
        ),
    ]
