# Generated by Django 4.1.4 on 2022-12-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_users_userpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appid', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('TransactionPoints', models.IntegerField()),
            ],
        ),
    ]
