# Generated by Django 4.1.4 on 2022-12-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_remove_users_installedapps_remove_users_userpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
