# Generated by Django 4.1.4 on 2022-12-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_transactions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='AppId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
